sequenceDiagram
    autonumber
    participant User as User
    participant Main as __main__
    participant Model as FasterRCNNModel
    participant State as state
    participant Trainer as train()
    participant Dataset as Dataset (VOC, COCO,...)
    participant Optimizer as Optimizer
    participant TrainStep as model.train_step()
    participant Stats as TrainingStatistics
    participant Eval as evaluate()
    participant PR as PrecisionRecallCurveCalculator

    User->>Main: run `python -m pytorch.FasterRCNN --train ...`
    Main->>Main: parse args
    Main->>Main: validate options (backbone, ...)
    Main->>Main: create selected backbone
    Main->>Main: create FasterRCNN with options

    Main->>Trainer: func call

    Trainer->>Trainer: create train Dataset
    Trainer->>Trainer: create eval Dataset
    Trainer->>Trainer: create optimizer with model params
    Trainer->>Trainer: create CSVLog (if required)
    Trainer->>Trainer: create BestWeightsTracker (if required)

    Note over Trainer, Stats: Repeat by configured epoch number
    loop epochs (1 .. options.epochs)
        Trainer->>Trainer: create TrainingStatistics
        
        Note over Trainer,Stats: iterate over train data samples
        loop for each train sample
            Trainer->>Dataset: request sample
            Dataset-->>Trainer: yield sample

            Trainer->>TrainStep: model.train_step(optimizer, image_data, anchor_map, gt_boxes...)
            TrainStep->>Optimizer: compute grads & optimizer.step()
            TrainStep-->>Trainer: return loss
            
            Trainer->>Stats: pass loss
            Stats->>Stats: accumulate loss accross steps within epoch
            Stats-->>Trainer: return stats dict
            Trainer->>Trainer: update progbar
        end

        Trainer->>Trainer: save checkpoint (if required)
        Trainer->>Trainer: log to CSV file (if required)
        Trainer->>Trainer: keep track of best weights (if required)
    end

    Trainer->>Trainer: save final weights
    Trainer->>Trainer: save best weights (if required)
    
    Trainer->>Eval: func call
    Note over Model,PR: iterate over eval data samples
    loop for each eval sample
        Eval->>Dataset: request sample
        Dataset-->>Eval: yield sample

        Eval->>Model: pass image data
        Model-->>PR: return prediction
        PR->>PR: compute correctness of predictions and accumulate results 
    end
    PR->>Eval: return results
    Eval-->>Eval: print results

    Main-->>User: exit (training completed)

%% Notes:
%% - model.train_step performs forward, loss, backward, optimizer update
%% - evaluate runs model.predict per sample and computes mAP via PrecisionRecallCurveCalculator
